apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vms-dev
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'vms-dev'
    spec:
      project: "default"
      source:
        repoURL: git@github.com:nap-devops/nap-vms-deployment.git
        targetRevision: "development"
        path: 'visitor-management'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - values-tags-development.yaml
            - values-development.yaml
      destination:
        name: in-cluster
        namespace: vms-dev
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
