loki-stack:
  enabled: true
  test_pod:
    enabled: false
  promtail:
    fullnameOverride: promtail
    config:
      clients:
        - url: http://loki-log:3100/loki/api/v1/push
  loki:
    fullnameOverride: loki-log
    persistence:
      enabled: false
    config:
    alerting_groups: []
    rbac:
      pspEnabled: false

  grafana:
    enabled: true
    fullnameOverride: loki-log-grafana
    envRenderSecret: {}
    envFromSecret: google-oidc-secret
    rbac:
      pspEnabled: false
    image:
      tag: 8.5.13

    grafana.ini:
      server:
        root_url: https://grafana-loki.devops.napbiotec.io

      auth.generic_oauth:
        name: Google
        enabled: true
        allow_sign_up: true
        team_ids:
        allowed_organizations:
        client_id: ${GOOGLE_CLIENT_ID}
        client_secret: ${GOOGLE_CLIENT_SECRET}
        scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
        auth_url: https://accounts.google.com/o/oauth2/auth
        token_url: https://accounts.google.com/o/oauth2/token
        api_url: https://www.googleapis.com/oauth2/v1/userinfo
        role_attribute_path: to_string('Editor')
        allowed_domains: napbiotec.io
