domain: devops.napbiotec.io
grafanaBackend: loki-log-grafana

loki-stack:
  grafana:
    grafana.ini:
      server:
        root_url: https://grafana-loki.devops.napbiotec.io
        domain: grafana-loki.devops.napbiotec.io
