domain: devops.napbiotec.io
grafanaBackend: loki-log-production-grafana

helm-loki:
  loki-stack:
    grafana:
      grafana.ini:
        server:
          root_url: https://grafana-loki.devops.napbiotec.io
