apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: onix-v2-dev
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'onix-v2-dev'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/wintech-thai/onix-v2-argocd-apps.git
        targetRevision: "development" #Based on environment
        path: '.'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values-files/values-development.yaml

            # Kong
            - values-files/kong/kong-00-values.yaml
            # PostgreSQL
            - values-files/postgresql/postgresql-00-values.yaml
            # Redis
            - values-files/redis/redis-00-values.yaml

            # Onix-API
            - values-files/onix-api/onix-api-00-values.yaml
            - values-files/onix-api/onix-api-01-development-values.yaml
            - values-files/onix-api/onix-api-03-development-image-tag.yaml

            # Onix-Console
            - values-files/onix-console/onix-console-00-values.yaml
            - values-files/onix-console/onix-console-01-development-values.yaml
            - values-files/onix-console/onix-console-03-development-image-tag.yaml

            # Onix-Jobs
            - values-files/onix-jobs/onix-jobs-00-values.yaml
            - values-files/onix-jobs/onix-jobs-01-development-values.yaml
            - values-files/onix-jobs/onix-jobs-03-development-image-tag.yaml

            # Onix-Web-Scan
            - values-files/onix-web-scan/onix-web-scan-00-values.yaml
            - values-files/onix-web-scan/onix-web-scan-01-development-values.yaml
            - values-files/onix-web-scan/onix-web-scan-03-development-image-tag.yaml

            # Please-Scan-Web
            - values-files/please-scan-web/please-scan-web-00-values.yaml
            - values-files/please-scan-web/please-scan-web-01-development-values.yaml
            - values-files/please-scan-web/please-scan-web-03-development-image-tag.yaml
      destination:
        name: in-cluster
        namespace: onix-v2-development
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
