apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: genuine-dev
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'genuine-dev'
    spec:
      project: "default"
      source:
        repoURL: git@github.com:nap-devops/nap-devops-argocd-apps.git
        targetRevision: "{{name}}" #Based on environment
        path: 'manifests/genuine-dev'
      destination:
        name: in-cluster
        namespace: genuine-dev
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
