apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: genuine-docs-prod
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'genuine-docs-prod'
    spec:
      project: "default"
      source:
        repoURL: git@github.com:nap-devops/nap-genuine-docs-deployment.git
        targetRevision: "production"
        path: 'genuine-common'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - values-tags-production.yaml
            - values-production.yaml
      destination:
        name: in-cluster
        namespace: genuine-docs-prod
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
