apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: codecheck
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'codecheck-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: git@github.com:nap-devops/nap-devops-argocd-apps.git
        targetRevision: "{{name}}" #Based on environment
        path: 'manifests/codecheck'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - values-{{name}}.yaml
      destination:
        name: in-cluster
        namespace: codecheck
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
