{{- if .Values.backupRestore.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.backupRestore.namePrefix }}-backup-credentials
  #namespace: {{ .Values.backupRestore.app.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: {{ .Values.backupRestore.namePrefix }}-backup-credentials
    creationPolicy: Owner
  data:
    - secretKey: S3_KEY
      remoteRef:
        key: devhubs-backup-s3
        property: S3_KEY
        version: latest

    - secretKey: S3_SECRET
      remoteRef:
        key: devhubs-backup-s3
        property: S3_SECRET
        version: latest

    - secretKey: DISCORD_WEBHOOK
      remoteRef:
        key: devhubs-backup-s3
        property: DISCORD_WEBHOOK
        version: latest
{{- end }}
