domain: devops.napbiotec.io
domain2: napbiotec.io
domain3: aldamex.com
domain4: napbiotec.com

backendService: ingress-nginx-production-controller

ingress-nginx:
  enabled: true

  controller:
    service:
      enabled: true
      type: ClusterIP
      annotations:
        cloud.google.com/neg: '{"ingress": true}'
        cloud.google.com/backend-config: '{"default": "nginx-hc-config"}'
        cloud.google.com/app-protocols: '{"https":"HTTPS", "http":"HTTP"}'
