apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: soc
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: alertmanager-main
      namespace: monitoring
      port: web
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: 1
  retention: 600d
  retentionSize: 48GB
  ruleNamespaceSelector: {}
  ruleSelector: {}
  serviceMonitorSelector: {}
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 50Gi
