---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-credentials
spec:
  refreshInterval: 1h          # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: grafana-credentials  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "GRAFANA_USER"
      remoteRef:
        key: grafana-credentials
        version: latest
        property: GRAFANA_USER

    - secretKey: "GRAFANA_PASSWORD"
      remoteRef:
        key: grafana-credentials
        version: latest
        property: GRAFANA_PASSWORD
