apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: houston-codecheck-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.allow-http: "true" #Wordpress will redirect to https internally
spec:
  tls:
    - hosts:
      - {{ .Values.domainWordpress2 }}
      - www.{{ .Values.domainWordpress2 }}
      secretName: houston-cert
  rules:
    - host: {{ .Values.domainWordpress2 }}
      http:
        paths:
          - path: /houston
            pathType: Prefix
            backend:
              service:
                name: codecheck-external-ip
                port:
                  number: 80
  
    - host: www.{{ .Values.domainWordpress2 }}
      http:
        paths:
          - path: /houston
            pathType: Prefix
            backend:
              service:
                name: codecheck-external-ip
                port:
                  number: 80
