apiVersion: v1
kind: ConfigMap
metadata:
  name: ruby-filter-cm
data:
  filter.rb: |-
{{ .Files.Get "scripts/filter.rb" |  indent 4 }}
  load-cache.rb: |-
{{ .Files.Get "scripts/load-misp-cache.rb" |  indent 4 }}
