---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - webhook-sftp.{{ .Values.domain }}
  rules:
    - host: webhook-sftp.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.hookBackend }}
                port:
                  number: 8080
