apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: webhook-secret
spec:
  refreshInterval: 1h          # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: webhook-secret  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "WEBHOOK_USER"
      remoteRef:
        key: webhook-secret
        version: latest
        property: WEBHOOK

    - secretKey: "WEBHOOK_PASSWORD"
      remoteRef:
        key: webhook-secret
        version: latest
        property: WEBHOOK_PASSWORD
