apiVersion: v2
name: helm-orangehrm
description: A Helm chart for OrangeHRM
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: mysql
    version: "9.2.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled

  - name: "generic-app"
    alias: orangehrm
    condition: orangehrm.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"