orangehrm:
  enabled: true
  nameOverride: orangehrm

  pods:
    controller: deployment    
    image:
      name: docker.io/orangehrm/orangehrm
      tag: 5.3

    env:
      - name: ORANGEHRM_DATABASE_HOST
        value: orangehrm-production-mysql
    
      - name: ORANGEHRM_DATABASE_USER
        value: "root"

      - name: ORANGEHRM_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: orangehrm-db-login
            key: mariadb-password
            optional: false

      - name: ORANGEHRM_DATABASE_NAME
        value: "orangehrm"

      - name: PUID
        value: "998"

      - name: PGID
        value: "100"
        
mysql:
  enabled: true
  image:
    tag: 8.0.28
  auth:
    database: orangehrm
    existingSecret: orangehrm-db-login