replicaCount: 3
nameOverride: "sftp-gcs"
fullnameOverride: "sftp-gcs"

users:
  - user: hikvision
    password: "" #Password defined in vault instead
    bucket: napbiotec-sftp

service:
  type: LoadBalancer
  port: 2022
  annotations: {}

image:
  repository: danuk/k8s-sftp-gcs
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true
  capabilities:
    add:
    - SYS_ADMIN

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}