domain: grafana-k8s.devops.napbiotec.io
domain1: alm.devops.napbiotec.io
domain2: prom.devops.napbiotec.io

environment: production

kube-prometheus-stack:
  grafana:
    grafana.ini:
      server:
        root_url: grafana-k8s.devops.napbiotec.io
    grafana.ini:
      server:
        root_url: https://grafana-k8s.devops.napbiotec.io
        domain: grafana-k8s.devops.napbiotec.io
