domain: grafana-soc.devops.napbiotec.io

grafana:
  enabled: true

  fullnameOverride: grafana-soc
  envFromSecret: google-oidc-secret
  envFromSecrets:
    - name: es-secret
      optional: false

  envRenderSecret: {}

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus-SOC
        type: prometheus
        access: Server
        url: http://prometheus-operated.prometheus-soc.svc.cluster.local:9090

      - name: Loki-SOC
        type: loki
        access: Server
        url: http://loki-soc-query-frontend.loki-soc.svc.cluster.local:3100

      - name: ES-SOC
        type: elasticsearch
        access: Server
        url: https://es-soc-es-http.es-soc.svc.cluster.local:9200
        basicAuth: true
        basicAuthUser: ${ES_USER}
        basicAuthPassword: ${ES_PASSWORD}
        database: "metrics-*"
        jsonData:
          interval: null
          timeField: metrics.last_update_date
          esVersion: '8.0.0'
          tlsSkipVerify: true
          tlsAuthWithCACert: false

      - name: Loki-App
        type: loki
        access: Server
        url: http://loki-log-production.loki-log.svc.cluster.local:3100

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'SOC'
        orgId: 1
        folder: 'SOC'
        folderUid: ''
        type: file
        options:
          path: /var/lib/grafana/dashboards

  dashboardsConfigMaps:
    cm-logstash-dashboard: cm-logstash-dashboard
    cm-events-stat: cm-events-stat
    cm-dst-network-stat: cm-dst-network-stat
    cm-potential-intrusion: cm-potential-intrusion
    #cm-event-summ-by-date: cm-event-summ-by-date
    cm-misp-event-summ: cm-misp-event-summ
    cm-connection-summ: cm-connection-summ

  grafana.ini:
    log:
      level: debug
    server:
      root_url: "https://grafana-soc.devops.napbiotec.io"

    auth.generic_oauth:
      name: Google
      enabled: true
      allow_sign_up: true
      team_ids:
      allowed_organizations:
      client_id: ${GOOGLE_CLIENT_ID}
      client_secret: ${GOOGLE_CLIENT_SECRET}
      scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
      auth_url: https://accounts.google.com/o/oauth2/auth
      token_url: https://accounts.google.com/o/oauth2/token
      api_url: https://www.googleapis.com/oauth2/v1/userinfo
      role_attribute_path: to_string('Editor')
      allowed_domains: napbiotec.io
