logstash-syslog:
  enabled: true

  replicas: 1
  fullnameOverride: logstash-syslog #From Syslog to Kafka
  image: "grafana/logstash-output-loki"
  imageTag: 2.5.0-amd64

  service:
    type: LoadBalancer
    loadBalancerIP: 34.124.235.129 #gke-syslog-svc-1
    ports:
    - name: syslog-udp
      port: 5140 #443
      targetPort: 5140
      protocol: UDP

  extraEnvs:
    - name: DUMMY_FOR_RESTART #Change this when changin Ruby code in order to restart pod
      value: "0003"
  
    - name: LS_JAVA_OPTS
      value: "-Xmx256m -Xms256m"

  logstashConfig:
    logstash.yml: |
      http.host: "0.0.0.0"
      pipeline.ecs_compatibility: "disabled"

  extraVolumeMounts:
    - name: scripts
      mountPath: /scripts/
      readOnly: true

  extraVolumes:
    - name: scripts
      configMap:
        name: ruby-filter-cm

  logstashPipeline:
    logstash.conf: |
      # echo "message" | nc -q0 syslog.devops.napbiotec.io 5140
      # logger -P 5140 -d -n syslog.devops.napbiotec.io "hello-abc,world this is seub"

      input {
        syslog {
          port => 5140
        }
      }

      filter {
        mutate {
          add_field => {
            "job" => "syslog"
          }
        }

        grok {
          match => {
            "message" => "(?<category>(.+?)),"
          }
        }

        ruby {
          path => "/scripts/filter.rb"
          script_params => { "category" => [category] }
        }
      }

      output {
        stdout { codec => rubydebug  }

        loki {
          url => "http://loki-soc-gateway.loki-soc.svc.cluster.local/loki/api/v1/push"
        }
      }   
