logstash-syslog:
  enabled: true

  replicas: 1
  fullnameOverride: logstash-syslog #From Syslog to Kafka
  image: "grafana/logstash-output-loki"
  imageTag: 2.5.0-amd64

  service:
    type: LoadBalancer
    loadBalancerIP: 34.124.235.129 #gke-syslog-svc-1
    ports:
    - name: syslog-udp
      port: 5140 #443
      targetPort: 5140
      protocol: UDP

  extraEnvs:
    - name: DUMMY_FOR_RESTART #If need to restart pod manually then change this
      value: "0012"
  
    - name: LS_JAVA_OPTS
      value: "-Xmx256m -Xms256m"

  logstashConfig:
    logstash.yml: |
      http.host: "0.0.0.0"
      pipeline.ecs_compatibility: "disabled"

  extraVolumeMounts:
    - name: scripts
      mountPath: /scripts/
      readOnly: true

  extraVolumes:
    - name: scripts
      configMap:
        name: ruby-filter-cm

  logstashPipeline:
    logstash.conf: |
      # echo "message" | nc -q0 syslog.devops.napbiotec.io 5140
      # logger -P 5140 -d -n syslog.devops.napbiotec.io "hello-abc,world this is seub"

      input {
        syslog {
          port => 5140
        }
      }

      filter {
        ruby {
          path => "/scripts/filter.rb"
          script_params => {}
        }

        memcached {
          hosts => ["memcached.memcached.svc.cluster.local"]
          namespace => "soc-ip"
          get => {
            "%{dst_ip}" => "misp_dst_ip"
          }
        }

        memcached {
          hosts => ["memcached.memcached.svc.cluster.local"]
          namespace => "soc-domain"
          get => {
            "%{domain}" => "misp_domain"
          }
        }

        if ![misp_dst_ip] {
          ruby {
            path => "/scripts/load-misp-cache.rb"
            script_params => {
              cached_field => 'misp_dst_ip'
              value_field => 'dst_ip'
            }
          }

          memcached {
            hosts => ["memcached.memcached.svc.cluster.local"]
            namespace => "soc-ip"
            set => {
              "[misp_dst_ip]" => "%{dst_ip}"
              "ttl" => 600 # 10 minutes
            }
          }
        }

        if ![misp_domain] {
          ruby {
            path => "/scripts/load-misp-cache.rb"
            script_params => {
              cached_field => 'misp_domain'
              value_field => 'domain'
            }
          }

          memcached {
            hosts => ["memcached.memcached.svc.cluster.local"]
            namespace => "soc-domain"
            set => {
              "[misp_domain]" => "%{domain}"
              "ttl" => 600 # 10 minutes
            }
          }            
        }

        ruby {
          path => "/scripts/process-misp-fields.rb"
        }

        mutate {
          # Remove temp fields, not to be shown in Loki
          remove_field => [ "misp_domain", "misp_dst_ip" ]
        }
      }

      output {
        #stdout { codec => rubydebug  }

        loki {
          url => "http://loki-soc-gateway.loki-soc.svc.cluster.local/loki/api/v1/push"
        }
      }   
