vector:
  fullnameOverride: vector-soc
  rbac:
    create: true

  serviceAccount:
    create: true

  extraVolumeMounts:
    - name: secrets
      mountPath: /secrets/
      readOnly: true

  extraVolumes:
    - name: secrets
      secret:
        secretName: gcp-sa

  customConfig:
    data_dir: "/vector-data-dir" #Do not change this if you don't know the impact
    sources:
      internal_metrics:
        type: internal_metrics

      pubsub_normalized_syslog:
        type: gcp_pubsub
        credentials_path: "/secrets/gcp-sa-file.json"
        project: "nap-devops-prod"
        subscription: "normalized-syslog-sub"        

    transforms:
      extract_dices:
        type: remap
        inputs:
          - pubsub_normalized_syslog
        source: |-
          syslog_json_str = .message
          . = parse_json!(string!(syslog_json_str))
          .ts = string!(.@timestamp)

          date_tokens = split!(.ts, "T")
          tokens = split(date_tokens[0], "-")

          .log = {
            "yyyymmdd": tokens[0] + tokens[1] + tokens[2],
            "yyyymm": tokens[0] + tokens[1],
            "yyyy": tokens[0],
            "category": .category,
            "value": 1
          }

      extract_metrics:
        type: log_to_metric
        inputs:
          - extract_dices
        metrics:
          - type: counter
            field: log.value
            name: event_count
            namespace: syslog
            tags:
              "yyyymmdd":  '{{ printf "{{%s}}" "yyyymmdd" }}'
              "yyyymm":  '{{ printf "{{%s}}" "yyyymm" }}'
              "yyyy":  '{{ printf "{{%s}}" "yyyy" }}'
              "category":  '{{ printf "{{%s}}" "category" }}'

    sinks:
      prometheus_event_exporter:
        #buffer:
        #  type: disk
        type: prometheus_exporter
        inputs: [extract_metrics]
        default_namespace: syslog
        address: 0.0.0.0:9090

      stdout:
        type: console
        inputs: [extract_metrics]
        encoding:
          codec: json
