apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.org/client-max-body-size: 50m
spec:
  ingressClassName: iap-nginx
  tls:
    - hosts:
      - {{ .Values.domain }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snipeit-production
                port:
                  number: 80
