apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-ruler-alerting-rules
data:
  generic-alert-rules.txt: |
    groups:
      - name: should_fire
        rules:
          - alert: LokiWatchdog
            expr: |
              sum(count_over_time({type="syslog"}[1m])) >= 1
            for: 4h
            labels:
              severity: none
            annotations:
              summary: "This is an alert meant to ensure that the entire Loki alerting is functional."

          - alert: UnknownCategoryError
            expr: |
              sum(count_over_time({type="syslog", category="unknown"}[15m])) >= 1
            for: 30s
            labels:
              severity: warning
            annotations:
              description: Found  {{ "{{" }} printf "%v" $value {{ "}}" }} unknown identifiable log line(s)

          - alert: SystemCategoryFound
            expr: |
              sum(count_over_time({type="syslog", category="system"}[15m])) >= 1
            for: 30s
            labels:
              severity: warning
            annotations:
              description: Found  {{ "{{" }} printf "%v" $value {{ "}}" }} line(s) of [system] category

          - alert: NoDataToSyslogError
            expr: |
              sum(count_over_time({type="syslog"}[5m])) <= 50
            for: 30s
            labels:
              severity: warning
            annotations:
              description: Found  {{ "{{" }} printf "%v" $value {{ "}}" }} line(s) of log which less than the threshold [50]
