apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-ruler-alerting-rules
data:
  generic-alert-rules.txt: |
    groups:
      - name: should_fire
        rules:
          - alert: LokiWatchdog
            expr: |
              1 + 1 > 0
            for: 4h
            labels:
              severity: none
            annotations:
              summary: "This is an alert meant to ensure that the entire Loki alerting is functional."

          - alert: UnknownCategoryError1
            expr: |
              sum(count_over_time({type="syslog", category="unknown"}[1m])) >= 1
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: Found unknown identifiable log lines 1

          - alert: UnknownCategoryError2
            expr: |
              sum(count_over_time({type="syslog", category="firewall"}[1m])) >= 1
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: Found unknown identifiable log lines 2
