apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-ruler-alerting-rules
data:
  generic-alert-rules.txt: |
    groups:
      - name: should_fire
        rules:
          - alert: UnknownCategoryError
            expr: sum(count_over_time({type="syslog", category="unknown"}[1m])) >= 1
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: Found unknown identifiable log lines

          - alert: UnknownCategoryErrorTest
            expr: sum(count_over_time({type="syslog", category="firewall"}[1m])) >= 1
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: Found unknown identifiable log lines
