apiVersion: v2
name: helm-uptime-kuma
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for Uptime Kuma

dependencies:
  - name: "uptime-kuma"
    alias: uptime-kuma
    condition: uptime-kuma.enabled
    repository: "https://dirsigler.github.io/uptime-kuma-helm"
    version: "2.21.2"
