---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: orangehrm-db-login
spec:
  refreshInterval: 1h          # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: orangehrm-db-login  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "mysql-root-password" # For MySQL
      remoteRef:
        key: orangehrm-db-login
        version: latest

    - secretKey: "mysql-password" # For MySQL
      remoteRef:
        key: orangehrm-db-login
        version: latest

    - secretKey: "mariadb-password" # For OrangeHrm
      remoteRef:
        key: orangehrm-db-login
        version: latest
