apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orangehrm-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
    kubernetes.io/ingress.class: "iap-nginx"
spec:
  tls:
    - hosts:
      - {{ .Values.domain }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orangehrm-production
                port:
                  number: 80
