domain: 'kafka-ui.rtarf-prod.its-software-services.com'

kafka-ui:
  enabled: true
  fullnameOverride: kafka-ui
  envs:
    config:
      KAFKA_CLUSTERS_0_NAME: kafka-nap
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-nap-kafka-bootstrap.kafka-nap.svc.cluster.local:9092
      #KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
      #KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_READONLY: "false"
      AUTH_TYPE: "DISABLED"
      SECURITY_BASIC_ENABLED: "true"
