domain: devops.napbiotec.io

helm-loki:
  enabled: true
  exposes: {}

  grafana:
    adminPassword: "" #Set random password
    rbac:
      pspEnabled: false

  promtail:
    enabled: false

  loki-distributed:
    enabled: true
    fullnameOverride: loki-soc
    
    distributor:
      replicas: 1

    loki:
      replicas: 1 
      image:
        tag: 2.4.0
      rbac:
        pspEnabled: false

    gateway:
      replicas: 1
      basicAuth:
        enabled: false

    customParams:
      backendStorageType: gcs
      gcsBucket: nap-devops-prod-loki
      #gcsKeySecretName: gcp-sa

    compactor:
      enabled: true

    ruler:
      enabled: true
      extraVolumes:
        - name: loki-ruler-alerting-rules
          configMap:
            name: loki-ruler-alerting-rules
        - name: gcp-sa
          secret:
            secretName: gcp-sa
            items:
            - key: gcp-sa-file
              path: gcp-sa-file.json
      extraVolumeMounts:
        - name: loki-ruler-alerting-rules
          mountPath: "/etc/loki/rules/fake"
        - name: gcp-sa
          mountPath: "/secrets"
          readOnly: true
      extraEnv:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/gcp-sa-file.json
      storage:
        type: local
        local:
          directory: /etc/loki/rules
      ring:
        kvstore:
          store: memberlist
      #rule_path: /rules/alerts
      alertmanager_url: http://prometheus-alertmanager.monitoring.svc.cluster.local:9093
      external_url: http://alertmanager.xx

    querier:
      replicas: 1
      extraVolumes:
        - name: gcp-sa
          secret:
            secretName: gcp-sa
            items:
            - key: gcp-sa-file
              path: gcp-sa-file.json

      extraVolumeMounts:
        - name: gcp-sa
          mountPath: "/secrets"
          readOnly: true

      extraEnv:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/gcp-sa-file.json

    ingester:
      replicas: 1
      extraVolumes:
        - name: gcp-sa
          secret:
            secretName: gcp-sa
            items:
            - key: gcp-sa-file
              path: gcp-sa-file.json

      extraVolumeMounts:
        - name: gcp-sa
          mountPath: "/secrets"
          readOnly: true

      extraEnv:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/gcp-sa-file.json

    compactor:
      replicas: 1
      extraVolumes:
        - name: gcp-sa
          secret:
            secretName: gcp-sa
            items:
            - key: gcp-sa-file
              path: gcp-sa-file.json

      extraVolumeMounts:
        - name: gcp-sa
          mountPath: "/secrets"
          readOnly: true

      extraEnv:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/gcp-sa-file.json
