{
 "title": "000-1 - Log Count Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Syslog Rate Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "category" },
  {
   "title": "Syslog Rate Summary",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "e/s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate({type=\"syslog\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Syslog Rate Summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "e/s" } },
   "targets": [
    {
     "expr": "sum(rate({type=\"syslog\"}[$__interval]))",
     "legendFormat": "Event Rate"
    }
   ]
  },
  { "title": "Syslog Total Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Syslog Total Summary",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({type=\"syslog\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Syslog Total Summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(count_over_time({type=\"syslog\"}[$__interval]))",
     "legendFormat": "Event"
    }
   ]
  },
  { "title": "Syslog Summary By Category", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Syslog Summary By Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (category) (count_over_time(({type=\"syslog\"})[$__interval]))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Syslog Summary By Category",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (category) (count_over_time(({type=\"syslog\"})[$__interval]))",
     "legendFormat": "{{category}}"
    }
   ]
  }
 ]
}