apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gcp-sa
spec:
  refreshInterval: 1h          # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: sftp-gcloud-key  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "gcloud-key.json"
      remoteRef:
        key: gcp-sa
        version: latest
