apiVersion: v2
name: helm-phpmyadmin
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for PHP MyAdmin

dependencies:
  - name: "phpmyadmin"
    alias: phpmyadmin 
    condition: phpmyadmin.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "13.1.1"
