apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snipeit-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
spec:
  ingressClassName: iap-nginx
  tls:
    - hosts:
      - {{ .Values.domain }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snipeit-production
                port:
                  number: 80
