apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: platform
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: alertmanager-main
      namespace: monitoring
      port: web
  podMonitorNamespaceSelector:
    matchLabels:
      platform-monitoring: "true"
  podMonitorSelector: {}  
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: 1
  retention: 600d
  retentionSize: 48GB
  ruleNamespaceSelector:
    matchLabels:
      platform-monitoring: "true"
  ruleSelector: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000  
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector:
    matchLabels:
      platform-monitoring: "true"
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 50Gi
