apiVersion: v2
name: helm-web-sgl
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for web SGL

dependencies:
  - name: wordpress
    version: "18.1.23"
    repository: "https://charts.bitnami.com/bitnami"
    condition: wordpress.enabled

  - name: mysql
    version: "9.14.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled
