apiVersion: v2
name: helm-kanboard
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for Kanboard

dependencies:
  - name: "generic-app"
    alias: kanboard
    condition: kanboard.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"
