domain: kanboard.internal.napbiotec.io

#### Kanboard ####
kanboard:
  enabled: true
  nameOverride: kanboard
  podDisruptionBudget:
    enabled: false
  pods:
    strategy:
      type: Recreate
    controller: deployment
    image:
      name: ghcr.io/kanboard/kanboard
      tag: v1.2.28
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
      - name: 443-tcp
        containerPort: 443
        protocol: TCP
    volumeMounts:
      - name: plugin
        mountPath: /var/www/app/plugins
      - name: data
        mountPath: /var/www/app/data
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: kanboard-data
      - name: plugin
        persistentVolumeClaim:
          claimName: kanboard-plugin
    env:
      #- name: DEBUG
      #  value: "true"

      - name: PLUGIN_INSTALLER
        value: "true"

      - name: MAIL_SMTP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: kanboard-db-login
            key: smtp-password
            optional: false

      - name: MAIL_CONFIGURATION
        value: "true"

      - name: MAIL_FROM
        value: "kanboard.webmaster@napbiotec.io"

      - name: MAIL_SMTP_ENCRYPTION
        value: "ssl"

      - name: MAIL_SMTP_HELO_NAME
        value: "FQDN"

      - name: MAIL_SMTP_HOSTNAME
        value: "smtp.gmail.com"

      - name: MAIL_SMTP_PORT
        value: "465"

      - name: MAIL_SMTP_USERNAME
        value: "webmaster@napbiotec.io"

  ingress:
    enabled: false

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: http
        protocol: TCP
        name: http
      - port: 443
        targetPort: 443-tcp
        protocol: TCP
        name: 443-tcp
