apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vector-soc-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: Aggregator
      app.kubernetes.io/name: vector      
  namespaceSelector:
    matchNames:
      - vector-soc
  podMetricsEndpoints:
  - path: /metrics
    port: prometheus-even
