{
 "title": "005 - MISP Event Summary",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "User",
    "query": "label_values({dst_ip_alert!=\"\"}, possible_user)"
   },
   {
    "name": "dst_ip_alert",
    "label": "Dest IP",
    "query": "label_values({dst_ip_alert!=\"\"}, dst_ip_alert)"
   }
  ]
 },
 "panels": [
  {
   "title": "MISP - Destination IP Blacklist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Source User Summary",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({type=\"syslog\",dst_ip_alert!=\"\",dst_ip_alert=~\"${dst_ip_alert}\",possible_user=~\"${user}\"}[$__interval])) by (possible_user)",
     "legendFormat": "{{possible_user}}"
    }
   ]
  },
  {
   "title": "Destination IP Blacklist Summary",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({type=\"syslog\",dst_ip_alert!=\"\",dst_ip_alert=~\"${dst_ip_alert}\",possible_user=~\"${user}\"}[$__interval])) by (dst_ip_alert)",
     "legendFormat": "{{dst_ip_alert}}"
    }
   ]
  },
  {
   "title": "Destination IP Blacklist By Source Summary",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({type=\"syslog\",dst_ip_alert!=\"\",dst_ip_alert=~\"${dst_ip_alert}\", possible_user=~\"${user}\"}[$__interval])) by (dst_ip_alert, possible_user)",
     "legendFormat": "{{possible_user}} -> {{dst_ip_alert}}"
    }
   ]
  }
 ]
}