---
# For some reason we are not able to generate cert by Cert Manager
# This is the workaround, use Goolge Manage Cert instead
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert-aldamex-thailand
spec:
  domains:
    - 'www.{{ .Values.domain7 }}'
    - '{{ .Values.domain7 }}'
