---
# For some reason we are not able to generate cert by Cert Manager
# This is the workaround, use Goolge Manage Cert instead
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert-aldamex-thailand
spec:
  domains:
    - 'www.{{ .Values.domain7 }}'
    - '{{ .Values.domain7 }}'
---
# For some reason we are not able to generate cert by Cert Manager
# This is the workaround, use Goolge Manage Cert instead
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: internal-napbiotec-io
spec:
  domains:
    - 'alfresco-dev.{{ .Values.domain8 }}'
    - 'orangecrm-dev.{{ .Values.domain8 }}'
    - 'alfresco.{{ .Values.domain8 }}'
    - 'orangecrm.{{ .Values.domain8 }}'
