---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ing-1
  annotations:
    kubernetes.io/ingress.allow-http: 'false'
    kubernetes.io/ingress.global-static-ip-name: gke-ingress-1
spec:
  tls:
    - secretName: nginx-cert
    - secretName: nginx-cert-admx
    - secretName: nginx-cert-napbiotec
  rules:
    - host: '*.{{ .Values.domain }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443
    - host: '*.{{ .Values.domain2 }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443
    - host: '{{ .Values.domain2 }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443                  
    - host: '*.{{ .Values.domain3 }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443
    - host: '{{ .Values.domain3 }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443
