apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
spec:
  secretName: nginx-cert
  dnsNames:
    - '*.{{ .Values.domain }}'
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert-napbiotec
spec:
  secretName: nginx-cert-napbiotec
  dnsNames:
    - '{{ .Values.domain2 }}'
    - '*.{{ .Values.domain2 }}'
  issuerRef:
    name: lets-encrypt-issuer-top-prod
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert-admx
spec:
  secretName: nginx-cert-admx
  dnsNames:
    - '{{ .Values.domain3 }}'
    - '*.{{ .Values.domain3 }}'
  issuerRef:
    name: lets-encrypt-issuer-top-prod
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert-napbiotec-com
spec:
  secretName: nginx-cert-napbiotec-com
  dnsNames:
    - '{{ .Values.domain4 }}'
    - '*.{{ .Values.domain4 }}'
  issuerRef:
    name: lets-encrypt-issuer-top-prod
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert-genuine-napbiotec-io
spec:
  secretName: nginx-cert-genuine-napbiotec-io
  dnsNames:
    - '{{ .Values.domain5 }}'
    - '*.{{ .Values.domain5 }}'
    - '{{ .Values.domain6 }}'
    - '*.{{ .Values.domain6 }}'    
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
