wordpress:
  replicaCount: 1
  wordpressScheme: https
  image:
    tag: 5.9.1

  ingress:
    ingressClassName: nginx
    enabled: true
    hostname: aldamex.devops.napbiotec.io

  service:
    type: ClusterIP