wordpress:
  replicaCount: 1
  wordpressScheme: https
  wordpressUsername: admin
  existingSecret: 'wordpress-user-login'

  image:
    tag: 5.9.1

  ingress:
    ingressClassName: nginx
    enabled: true
    hostname: aldamex.devops.napbiotec.io

  service:
    type: ClusterIP

  mariadb:
    auth:
      database: wordpress
      existingSecret: wordpress-db-login
