---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: kanboard-db-login
spec:
  refreshInterval: 1h          # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: kanboard-db-login  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "mariadb-user" # For MariaDB
      remoteRef:
        key: kanboard-db-login
        property: DB_USER
        version: latest

    - secretKey: "mariadb-root-password" # For MariaDB
      remoteRef:
        key: kanboard-db-login
        property: DB_ROOT_PASSWORD
        version: latest

    - secretKey: "mariadb-password" # For MariaDB
      remoteRef:
        key: kanboard-db-login
        property: DB_PASSWORD
        version: latest

    - secretKey: "mariadb-replication-password" # For MariaDB
      remoteRef:
        key: kanboard-db-login
        version: latest
        property: DB_REP_PASSWORD
